export const SHOW_LOADER = "SHOW_LOADER"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED"
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const REMOVE_EMAIL = "REMOVE_EMAIL";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const REMOVE_FORGOT_PASSWORD = "REMOVE_FORGOT_PASSWORD";
export const REMOVE_OTP = "REMOVE_OTP";
export const VERIFY_OTP = "VERIFY_OTP";
export const RESSET_PASSWORD = "RESSET_PASSWORD";
export const LOGOUT = "LOGOUT";
export const RESET_PASSWORD = "RESET_PASSWORD";



export const SHOW_TOAST = "SHOW_TOAST";



export const ADMIN_DATA = "ADMIN_DATA"
export const UPDATE_ADMIN = "UPDATE_ADMIN"
export const SINGUP_ADMIN = "SINGUP_ADMIN"


export const CUSTOMER_DATA = "CUSTOMER_DATA"
export const CUSTOMER_DETAILS = "CUSTOMER_DETAILS"
export const CUSTOMER_STATUS_UPDATTE = "CUSTOMER_STATUS_UPDATTE"
export const CUSTOMER_PROFILE_UPDATE = "CUSTOMER_PROFILE_UPDATE"


export const DASHBOARD_COUNT = "DASHBOARD_COUNT"


export const CUSTOMER_ORDER = "CUSTOMER_ORDER"
export const ORDER_DETAILS = "ORDER_DETAILS"
export const DESIGNER_ORDER_DETAILS = "DESIGNER_ORDER_DETAILS"
export const DESIGNER_ORDER_LIST = "DESIGNER_ORDER_LIST"

export const TRANSACTION_DETAILS = "TRANSACTION_DETAILS"
export const DESIGNER_TRANSACTION_DETAILS = "DESIGNER_TRANSACTION_DETAILS"


export const DESIGNER_DATA = "DESIGNER_DATA"
export const DESIGNER_DETAILS = "DESIGNER_DETAILS"
export const DESIGNER_PROFILE_UPDATE = "DESIGNER_PROFILE_UPDATE"
export const DESIGNER_STATUS_UPDATTE = "DESIGNER_STATUS_UPDATTE"


export const COLLECTION_DETAILS = "COLLECTION_DETAILS"
export const COLLECTION_ADD = "COLLECTION_ADD"


export const COLOURS_DETAILS = "COLOURS_DETAILS"


export const SIZE_DETAILS = "SIZE_DETAILS"
export const SIZE_LIST = "SIZE_LIST"
export const SIZE_STATUS_UPDATTE = "SIZE_STATUS_UPDATTE"

 


export const ADVERTISEMENT_DETAILS = "ADVERTISEMENT_DETAILS"
export const ADVERTISEMENT_ADD = "ADVERTISEMENT_ADD"
export const ADVERTISEMENT_STATUS_UPDATTE = " ADVERTISEMENT_STATUS_UPDATTE"

export const CATEGORY_DETAILS = "CATEGORY_DETAILS"
export const CATEGORY_ADD = "CATEGORY_ADD"
export const CATEGORY_UPDATE = "CATEGORY_UPDATE"
export const CATEGORY_STATUS_UPDATTE = "CATEGORY_STATUS_UPDATTE"


export const PRODUCT_DATA = "PRODUCT_DATA"
export const PRODUCT_ADD  = "PRODUCT_ADD"
export const PRODUCT_STATUS_UPDATTE = "PRODUCT_STATUS_UPDATTE"






export const ADD_MODAL = "ADD_MODAL"
export const ADD_SIZE_MODAL = "ADD_SIZE_MODAL"
export const ADD_COLOURS_MODAL = "ADD_COLOURS_MODAL"
export const DELETE_MODAL = "DELETE_MODAL"
export const ADD_CATEGORY_MODAL = "ADD_CATEGORY_MODAL"
export const ADD_PRODUCT_MODAL = "ADD_CATEGORY_MODAL"
export const EDIT_MODAL = "EDIT_MODAL"
export const  EDIT_ADMIN_MODAL = "EDIT_ADMIN_MODAL"
export const CHANGE_PASSWORD_MODAL = "CHANGE_PASSWORD_MODAL"
export const SIGNUP_MODAL = "SIGNUP_MODAL"




export const IMAGE_ADD = "IMAGE_ADD"

// Active id

export const SET_ACTIVE_CAT = "SET_ACTIVE_CAT"
export const SET_ACTIVE_DESIGNER = "SET_ACTIVE_DESIGNER"
export const SET_ACTIVE_COLLECTION = "SET_ACTIVE_COLLECTION"
export const SET_ACTIVE_COLOURS = "SET_ACTIVE_COLOURS"
export const SET_ACTIVE_CUSTOMER = "SET_ACTIVE_CUSTOMER"
export const SET_ACTIVE_ORDER = "SET_ACTIVE_ORDER"
export const SET_ACTIVE_DESIGNER_ORDER = "SET_ACTIVE_DESIGNER_ORDER"
export const SET_ACTIVE_PRODUCT = "SET_ACTIVE_PRODUCT"
export const SET_ACTIVE_SIZE = "SET_ACTIVE_SIZE"
export const SET_ACTIVE_ADMIN = "SET_ACTIVE_ADMIN"
export const SET_ACTIVE_ADVERTISEMENT = "SET_ACTIVE_ADVERTISEMENT"


export const SET_ALL_ID = "SET_ALL_ID"



